// <auto-generated />
using System;
using GrpcServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrpcServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210607171601_SecondStep")]
    partial class SecondStep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrpcServer.Models.Aposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAposta")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstrelasId")
                        .HasColumnType("int");

                    b.Property<int>("NumerosId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstrelasId");

                    b.HasIndex("NumerosId");

                    b.ToTable("Apostas");
                });

            modelBuilder.Entity("GrpcServer.Models.Estrelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estrela1")
                        .HasColumnType("int");

                    b.Property<int>("Estrela2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estrelas");
                });

            modelBuilder.Entity("GrpcServer.Models.Numeros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Numero1")
                        .HasColumnType("int");

                    b.Property<int>("Numero2")
                        .HasColumnType("int");

                    b.Property<int>("Numero3")
                        .HasColumnType("int");

                    b.Property<int>("Numero4")
                        .HasColumnType("int");

                    b.Property<int>("Numero5")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("GrpcServer.Models.Aposta", b =>
                {
                    b.HasOne("GrpcServer.Models.Estrelas", "Estrelas")
                        .WithMany("Apostas")
                        .HasForeignKey("EstrelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrpcServer.Models.Numeros", "Numeros")
                        .WithMany("Apostas")
                        .HasForeignKey("NumerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
